### ISSUE TITLE
Song Doesn't Finish Loading (When "/" is in the Title)

### ISSUE THREAD

**Issue by bradbus** [deepjyoti30/ytmdl-web-v2#22] opened 2021-05-29 04:18 UTC
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: Google Chrome
- Version: Version 91.0.4472.77 (Official Build) (64-bit)

## Console Log

?

## Description

When attempting to download a particular song, "No Sugar Tonight / New Mother Nature" by The Guess Who, the song would not finish loading after selecting the audio and metadata. I have previously successfully downloaded at least 30 songs without issue, none of which have had the "/" character in the title like this one did, which leads me to believe that the "/" character is the thing causing an issue. I have since tried other songs with the character in the title including "War Pigs / Luke's Wall" by Black Sabbath, "Holiday / Boulevard of Broken Dreams" by Green Day, and "Foreplay / Long Time" by Boston. They have all failed and resulted in the same issue happening. I of course don't know for a fact that the "/" is the problem, but I suspect it to be and think it is safe to say that it is the problem. 

I have only tried it on the web site because I could not figure out how to set the program up the other way, additional help would be appreciated. 

I have also tried downloading "No Sugar Tonight / New Mother Nature" in Firefox and Microsoft Edge, neither worked. And Internet Explorer couldn't even load the web site. I suspect that no other browser would work either. It wouldn't work on my phone either.

I really like this app, and I think it is very neat and well made. Thanks in advance for any help!

## Expected Behaviour

The behaviour I expect is the site to finish telling me "Getting the song ready for you..." after a few seconds. However, after waiting several seconds, and many minutes; none of the songs I attempted with "/" in the title ever finished and gave me a download button, which is what I expect to happen.

**Comment by deepjyoti30** [comment] 2021-06-11 08:09
@bradbus I will take a look about that. It is possible that the `/` might be causing an issue.

After you faced the issue with the song not downloading because of the `/`, did you try downloading some other song without the slash on it? If you did, then did it work?

**Comment by bradbus** [comment] 2021-06-11 12:04
> @bradbus I will take a look about that. It is possible that the `/` might be causing an issue.
> 
> After you faced the issue with the song not downloading because of the `/`, did you try downloading some other song without the slash on it? If you did, then did it work?

Yes it did work with every other song I tried. One idea as to what it could be is the filename, since Windows doesn't allow the slash character, but it kind of doesn't make sense to me why it would be the problem and not let me download it in the first place, just an idea, though I imagine the problem is something else.

**Comment by deepjyoti30** [comment] 2021-06-14 14:24
@bradbus The problem might be probably what you mentioned, the `/` in the title. I will add some fixes to make the / normalized from the URL.

**Comment by deepjyoti30** [comment] 2021-08-30 14:32
@bradbus The issue is fixed in the commit mentioned. I cross checked with the song you shared as well, it's working fine!

**Closed** 2021-08-30 14:32 UTC
Labels: bug
