### ISSUE TITLE
"Explicit lyrics" songs being unable to be downloaded or even viewed

### ISSUE THREAD

**Issue by BalintXHD** [deepjyoti30/ytmdl-web-v2#82] opened 2024-04-11 18:14 UTC
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: Firefox
- Version: probably latest stable

## Console Log

nothing out of ordinary

## Description

Title.
example urls: 
https://www.youtube.com/watch?v=lYYLH9_jVaE
https://youtu.be/HW655mV6eX4

## Expected Behaviour

Being able to download it. I understand that without an adult account it would be difficult for ytdl to download it, so most likely an error message popping up about this.

**Comment by deepjyoti30** [comment] 2024-04-12 02:17
Trying to download on my local, I do get the `Video Unavailable` error:

![https://i.imgur.com/QzJIJqv.png](https://i.imgur.com/QzJIJqv.png)

Do you not get the same?

**Comment by BalintXHD** [comment] 2024-04-12 13:09
I don't use the local version. Can you login using an adult account into yt-dl? That might fix it for local.

**Comment by BalintXHD** [comment] 2024-04-12 13:11
Somehow this url "works" meaning it does not error out as "try another url" but still doesnt download it. (https://www.youtube.com/watch?v=iRZEQoMk3B0)

**Comment by deepjyoti30** [comment] 2024-04-13 14:27
> Can you login using an adult account into yt-dl

AFAICT yt-dl allows providing cookies but there's probably no way to directly login using an adult account.



> Somehow this url "works" meaning it does not error out as "try another url" but still doesnt download it. (https://www.youtube.com/watch?v=iRZEQoMk3B0)

This one works on my end without any issues at all. Downloads fine and no errors. Can you confirm if you are on the latest version of `yt-dlp`?

**Comment by BalintXHD** [comment] 2024-04-13 18:23
> Can you confirm if you are on the latest version of yt-dlp?

I'm using the web app. (Clarification: https://ytmdl.deepjyoti30.dev/)

I did successfully downloaded a song in the meantime, however for some reason even in this normal song ( https://youtu.be/Wd9iZG_CM8I ) I still have issues.
Console (Firefox):

> Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by deepjyoti30** [comment] 2024-04-14 12:44
My bad. I thought you were talking about the CLI version. I am looking into the issue. Have found the cause for it. Will let you know once the fix is live!

**Comment by deepjyoti30** [comment] 2024-04-14 14:00
@BalintXHD The issue is fixed now. Please give it another try. I have also verified that the above URL works. Feel free to re-open if the issue is not fixed.

**Closed as completed by deepjyoti30** 2024-04-14 14:00 UTC
Labels: bug
