### ISSUE TITLE
3 problems found with the V2 Wepp Application of ytmdl

### ISSUE THREAD

**Issue by veillax1354** [deepjyoti30/ytmdl-web-v2#49] opened 2022-04-11 18:39 UTC
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: <Chrome>
- Version: Version 101.0.4951.26 (Official Build) beta (64-bit)

## Console Log

```
Console Log could not be located at the time.
```

## Description

3 problems were found while using the V2 Web App version of ytmdl 

- Page gets stuck on 'Your Song is Ready' page without the album cover art or download button
- Song Search does not come up with songs using Youtube link or song name
- Metadata search comes up with faulty metadata

## Expected Behaviour

- The page was expected to load fully appearing with all metadata, and a download button
- The 'Song Search' functionality was expected to find with the proper song using the Youtube link input as well as song name
- The ytmdl automatic metadata search was expected to find the proper metadata for the song requested

**Comment by Veillax135** [comment] 2022-04-11 18:40
I could not find a console log from my browser at the time.

**Comment by lupus0802** [comment] 2022-04-20 08:29
For me the page gets stuck too.
When I use a link on "Extracting title"
When I use a string on "Getting your song ready"

Perhaps the API Key isn't working any, or something like that?

**Comment by deepjyoti30** [comment] 2022-05-05 18:13
Thanks for the issue. I am aware of this happening at times for a few songs. I have recently updated the API to start using the latest version of ytmdl, please consider testing out the website now and report back here if you still face the same issue.

Also, exact song names that failed would be helpful to debug the issue.

**Comment by lupus0802** [comment] 2022-05-05 19:01
Hey, searching for the song by name has worked now, however I'm stuck on [https://ytmdl.deepjyoti30.dev/metadata?videoId=UstE6yTlwcU&query=Dear%20Brave%20kano](https://ytmdl.deepjyoti30.dev/metadata?videoId=UstE6yTlwcU&query=Dear%20Brave%20kano) now. (I selected the song for testing purposes)

**Comment by lupus0802** [comment] 2022-05-05 19:03
Using the [URL](https://www.youtube.com/watch?v=UstE6yTlwcU) directly doesn't work either, I believe it is stuck at getting the metadata.

**Comment by jlnhlfan** [comment] 2022-05-08 00:09
On my end, this is happening as well; it's stuck on "Your song is ready", but no download link.

**Comment by deepjyoti30** [comment] 2022-05-09 12:37
@lupus0802 For the query term, it seems there are no searches found. Could you try with another term?

**Comment by MmeK** [comment] 2022-05-10 05:42
The page getting stuck on "your song is ready" happens for me as well. Checking the network requests it seems that the POST request to this endpoint: https://apis.deepjyoti30.dev/v2/ytmdl/download returns a 400 status code with the message "Seems like the video ID passed is not valid."
This is the url of the video: https://www.youtube.com/watch?v=tvTRZJ-4EyI
In the payload section of the request video_id is passed like this: video_id: "tvTRZJ-4EyI"
Seems to me that the ID is correct.

**Comment by jlnhlfan** [comment] 2022-05-10 05:46
> The page getting stuck on "your song is ready" happens for me as well. Checking the network requests it seems that the POST request to this endpoint: https://apis.deepjyoti30.dev/v2/ytmdl/download returns a 400 status code with the message "Seems like the video ID passed is not valid." This is the url of the video: https://www.youtube.com/watch?v=tvTRZJ-4EyI In the payload section of the request video_id is passed like this: video_id: "tvTRZJ-4EyI" Seems to me that the ID is correct.

Going to that first link brings up a "Method Not Allowed" error on my end.

**Comment by Devnol** [comment] 2022-06-11 10:09
Can confirm same happens to me as well, searched Sweet Child o' Mine by name and by url, "Your song is Ready!" appears but no button or anything.
OS: macOS 12.4
Browser: Firefox, uBlock installed but disabled (I somehow still don't get ads), same with Enhanced tracking protection
Network tab shows a 400 Bad request with "Seems like the video ID passed is not valid." as a response.

**Comment by deepjyoti30** [comment] 2022-07-10 05:22
Apologies for the delayed response everyone, the issue is fixed now. I finally got some time to dig around the logs and figure out what was wrong with the download process.

It is fixed now, I just tested the latest deployed version, you guys can test it out and let me know if anything seems off.

@Veillax135 @Devnol @jlnhlfan @MmeK @lupus0802

**Comment by deepjyoti30** [comment] 2023-02-18 15:22
Closing the issue as the issue is fixed now!

**Closed by deepjyoti30** 2023-02-18 15:22 UTC
Labels: bug
