### ISSUE TITLE
Youtube songs not working on web app

### ISSUE THREAD

**Issue by otterfree** [deepjyoti30/ytmdl-web-v2#70] opened 2023-02-27 19:47 UTC
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: Firefox
- Version: 110.0

I've also tried on Microsoft Edge and the issue is present on that browser as well.

## Description

Page gets stuck on 'Your Song is Ready' page without the album cover art or download button. This happens for every song I've tried to download, no matter if I input a link or search by name. Force refreshing kicks me back to the home page.

**Comment by Saiboogu** [comment] 2023-03-02 03:34
I'm running it locally and encountering the same behavior. 

Using image: ghcr.io/deepjyoti30/ytmdl-web:latest

The container is only producing http access logs with no signs of the error.

**Comment by deepjyoti30** [comment] 2023-03-05 14:37
@Saiboogu @otterfree Thanks for reporting the issue. This seems to be a new issue. ytmdl was working as of the last release that I made of the app (after a few fixes). Let me fix the issue and I will update here.

**Comment by deepjyoti30** [comment] 2023-03-05 15:47
@Saiboogu @otterfree The issue is now fixed. I just tested the website. You guys can check it out and report here. 

I am closing the issue now. Feel free to re-open it in case you see the issue.

**Closed by deepjyoti30** 2023-03-05 15:47 UTC
Labels: bug
