### ISSUE TITLE
Failed to load metadata for the song.

### ISSUE THREAD

**Issue by BalintXHD** [deepjyoti30/ytmdl-web-v2#72] opened 2023-03-18 10:22 UTC
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: <Firefox>

## Description

Only "The Bad Touch" in metadata search. "Failed to load metadata for the song. Please enter the song name only without artist name etc" message on screen.
(URL: https://www.youtube.com/watch?v=l77qrAnW1N4)
## Expected Behaviour

Loading the metadata because only song name is in query.

**Comment by deepjyoti30** [comment] 2023-03-18 15:31
@BalintXHD I am unable to reproduce this. I just tried with the above URL and exact same query and it is indeed returning metadata results for me.

Can you try again?

**Comment by BalintXHD** [comment] 2023-04-30 08:56
Sorry for not writing back. I had a lot to do, but I did bypass this issue with that song. I enabled only manual metadata editing and it worked.

**Comment by BalintXHD** [comment] 2023-04-30 08:59
I tried again now, it still doesn't work. (another url that doesn't work is this: https://www.youtube.com/watch?v=Fs-p78KJ5I4 )

**Comment by deepjyoti30** [comment] 2023-05-31 16:51
@BalintXHD Thanks for writing back, seems like the issue is specific to the above video, something crashes for this video only, otherwise it works fine. I'll look into this.

**Comment by deepjyoti30** [comment] 2023-05-31 17:11
@BalintXHD Just a heads up, I have debugged the issue and added a fix for it. Will be live soon. I will close the issue once I confirm that the issue is fixed! Thanks once again for reporting it.

**Comment by deepjyoti30** [comment] 2023-06-01 16:59
Closing as the issue is fixed

**Closed by deepjyoti30** 2023-06-01 16:59 UTC
Labels: bug
