### ISSUE TITLE
Stuck at 'Your Song Is Ready!' even though song works.

### ISSUE THREAD

**Issue by otterfree** [deepjyoti30/ytmdl-web-v2#76] opened 2023-08-11 02:20 UTC
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## How was Ytmdl Web run

- [ ] Locally
- [x] On the official page

## Browser Details

- Name: Firefox

## Description

Download link unavailable when trying to download. I have to run some songs through the web app multiple times to download them. It's frustrating when trying to do multiple songs. I recorded it to show the issue, download link becomes available after a minute of trying: https://www.youtube.com/watch?v=pBh0t_MCA9c

## Expected Behaviour

I want to be able to download songs on the first try.

**Comment by deepjyoti30** [comment] 2023-08-25 17:35
Hey guys, apologies about the late response, the issue is fixed now.

You can retry and report back here if it's not fixed. I will close this as I have confirmed the added fix works.

**Closed by deepjyoti30** 2023-08-25 17:35 UTC
Labels: bug
